In [ ]:
import time
import numpy as np

size_of_vec = 1000000

def pure_python_version():
  t1 = time.time()
  X = range(size_of_vec)
  Y = range(size_of_vec)
  Z = [X[i] + Y[i] for i in range(len(X))]
  return time.time() - t1

def numpy_version():
  t1 = time.time()
  X = np.arange(size_of_vec)
  Y = np.arange(size_of_vec)
  Z = X+Y
  return time.time() - t1

t1 = pure_python_version()
t2 = numpy_version()

t1 = pure_python_version()
t2 = numpy_version()

print(f'''Waktu running pure pythong adalah {round(t1,4)} detik.
Waktu running versi numpy adalah {round(t2,4)} detik.
Numpy di contoh ini {(round((t1/t2),4))} kali lebih cepat!''' )

Waktu running pure pythong adalah 0.265 detik.
Waktu running versi numpy adalah 0.0064 detik.
Numpy di contoh ini 41.6561 kali lebih cepat!


In [ ]:
#1D Array

my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [ ]:
print(np.array(my_list))

[1 2 3]


In [ ]:
#2D Array
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#3D Array

my_list3 = [
            [[1,2,3],[4,5,6],[7,8,9]],
            [[10,11,12],[13,14,15],[16,17,18]],
            [[19,20,21],[22,23,24],[25,26,27]]
]
print(np.array(my_list3))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
#Create Numpy Arrays arange

np.arange(0,10) #Start (0 by default), Stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2) #Start, Stop, Step

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#Creating Numpy Arrays zeros and ones

np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Creating Numpy Arrays eye

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Creating Numpy Arrays linspace

np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
#Creating Numpy Arrays random.rand

np.random.rand(2)

array([0.02681317, 0.52002534])

In [ ]:
np.random.rand(5,5)

array([[0.42500147, 0.21867098, 0.03579619, 0.89957885, 0.80659211],
       [0.36055554, 0.27329158, 0.83406344, 0.47964288, 0.21893606],
       [0.45953834, 0.67710393, 0.42549357, 0.08889236, 0.48623798],
       [0.28640344, 0.19543173, 0.43217074, 0.95240682, 0.33912222],
       [0.45009339, 0.40933569, 0.24520354, 0.84257248, 0.72854728]])

In [ ]:
#Creating Numpy Arrays random.randn

np.random.randn(2)

array([0.92524393, 1.34602205])

In [ ]:
np.random.randn(5,5)

array([[-0.86806816,  1.2002777 , -0.08186951,  0.08259847, -1.23244142],
       [-0.93433512,  0.05545823,  0.12857259,  1.06018469,  0.46094411],
       [ 0.38804737, -1.06162374,  2.00374759,  1.62418059,  0.03170294],
       [ 0.66045036, -2.66260284, -1.7315379 , -0.30750817,  0.75739144],
       [-1.07629053,  1.45119715,  0.50238922, -1.9511941 , -1.03221009]])

In [ ]:
#Creating Numpy Arrays random.randint

np.random.randint(1,100)

50

In [ ]:
np.random.randint(1,100,10)

array([46, 95,  2, 64, 27, 20, 92, 96, 24, 92])

In [ ]:
#Array Attributes and Methods - Shape

my_list = [1,2,3]
array_1d = np.array(my_list)

my_list2 = [[1,2,3],[4,5,3],[7,8,9]]
array_2d = np.array(my_list2)

my_list3 = [
            [[1,2,3],[4,5,3],[7,8,9]],
            [[10,11,12],[13,14,15],[16,17,18]],
            [[19,20,21],[22,23,24],[25,26,27]]
]
array_3d = np.array(my_list3)

In [ ]:
array_1d.shape

(3,)

In [ ]:
array_2d.shape

(3, 3)

In [ ]:
array_3d.shape

(3, 3, 3)

In [ ]:
#Array Attributes and Methods - reshape

np.array(my_list)

array([1, 2, 3])

In [ ]:
arr = np.arange(0,25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

In [ ]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 3, 7, 8, 9])

In [ ]:
array_2d.reshape(-1).shape

(9,)

In [ ]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  3,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [ ]:
array_3d.reshape(-1).shape

(27,)

In [ ]:
ranarr = np.random.randint(0,40,10)
print(ranarr)

[ 1 23 15 28  2 16 33  9 23 27]


In [ ]:
ranarr.max()

33

In [ ]:
ranarr.argmax()

6

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmin()

0

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr1 = np.linspace(0,10,10)
arr1.dtype

dtype('float64')

In [103]:
#New Array Arr
import numpy as np
arry = np.arange(1,11)
arry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
#Bracket Indexing and Selection
arry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arry[9]

10

In [106]:
arry[1:5]

array([2, 3, 4, 5])

In [107]:
arry[0:5]

array([1, 2, 3, 4, 5])

In [108]:
arry[0:10:2]

array([1, 3, 5, 7, 9])

In [109]:
#Slicing
arry[0:5]=100
arry

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [110]:
arry = np.arange(0,11)
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
slice_of_arry = arry[0:6]
slice_of_arry

array([0, 1, 2, 3, 4, 5])

In [112]:
slice_of_arry[:] = 99
slice_of_arry

array([99, 99, 99, 99, 99, 99])

In [113]:
arry

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [114]:
arry_copy = arry.copy()
arry_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [115]:
#Indexing a 2D array
arry_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arry_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [116]:
arry_2d[1]

array([20, 25, 30])

In [117]:
arry_2d[1][2]

30

In [118]:
arry_2d[0][2]

15

In [119]:
arry_2d[1,0]

20

In [120]:
arry_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arry_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [121]:
arry_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [122]:
arry_2d[:,2]

array([15, 30, 45])

In [125]:
#Fancy Indexing
arry = np.arange(0,11)
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
[arry[2],arry[5],arry[9]]

[2, 5, 9]

In [127]:
#Fancy Indexing
arry[[2,5,9]]

array([2, 5, 9])

In [128]:
arry[[5,9,3]]

array([5, 9, 3])

In [129]:
arry_2d = np.array(([5,10,5],[20,25,30],[35,40,45]))
arry_2d

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [130]:
arry_2d[[0,2]]

array([[ 5, 10,  5],
       [35, 40, 45]])

In [131]:
harry = np.arange(1,11)
print(harry)

[ 1  2  3  4  5  6  7  8  9 10]


In [132]:
harry > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [134]:
bool_harry = harry > 4
bool_harry

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [136]:
harry[bool_harry]

array([ 5,  6,  7,  8,  9, 10])

In [137]:
harry[harry>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [138]:
z = 2
harry[harry > z]

array([ 3,  4,  5,  6,  7,  8,  9, 10])